### ISSUE TITLE
Zip file with weights is not an archive

### ISSUE THREAD

**Issue by rybijakKarpiowy** [AMAAI-Lab/megamusicaps#12]
I tried to follow your set up instructions and after downloading the weights and running unzip, I get:

Archive:  spleeter_pretrained_weights.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of spleeter_pretrained_weights.zip or
        spleeter_pretrained_weights.zip.zip, and cannot find spleeter_pretrained_weights.zip.ZIP, period.

**Comment by dorienh** [comment]
Did you manage to solve it?

**Comment by rybijakKarpiowy** [comment]
wget downloaded a html file instead of the zip with weights, I opened the Google drive page in a browser and downloaded a zip that way
